#define SECONDS_CENTER_OFFSET_X 30 // 30
#define SECONDS_CENTER_OFFSET_Y 36 // 36
#define CONFIG_HAND_LENGTH_SEC 22
#define CONFIG_RADIUS_SECS_CIRCLE 23
#define CONFIG_HAND_LENGTH_HOUR PBL_IF_ROUND_ELSE(55,45)
#define CONFIG_HAND_LENGTH_MIN PBL_IF_ROUND_ELSE(75,65)
#define THICKNESS_MINUTES 4
#define THICKNESS_HOUR 4
#define THICKNESSMARKS 5
#define THICKNESS_SECONDS 2
#define HANDS_TOP_ROUND 86
#define HOUR_HAND_MINUS_ROUND 3
#define MINUTE_HAND_MINUS_ROUND 1

#define CENTER_HANDS_OFFSET 0
#define CENTER_HANDS_RADIUS 4
#define CONFIG_X_START_INFO_BOX 100
#define PATH_HANDS_INVERSE_LEGTH 15
#define PATH_HANDS_MINUTE_TICK_LIGHT 3
#define PATH_HANDS_MINUTE_TICK_BOLD 4
#define PATH_HANDS_HOUR_TICK_LIGHT 3
#define PATH_HANDS_HOUR_TICK_BOLD 4


#define CONFIG_CENTER_INFOLEFT_X 42
#define CONFIG_CENTER_INFOLEFT_Y 48
#define CONFIG_RADIUS_INFOLEFT_CIRCLE 23
#define CONFIG_CENTER_INFORIGHT_X 102
#define CONFIG_CENTER_INFORIGHT_Y 48
#define CONFIG_RADIUS_INFORIGHT_CIRCLE 23

#define MESSAGE_KEY_GET_WEATHER 1
//#define SECONDS_FOR_POLL 3600

#define WEATHER_TEMPERATURE_KEY 1
#define WEATHER_TEMPERATURE_FORE_KEY 2
#define SHOW_MINUTES_MARKS 1
#define SHOW_HOUR_MARKS 1
#define TIME_NUMERALS_FONT FONT_KEY_LECO_20_BOLD_NUMBERS
#define XPOS_12H PBL_IF_ROUND_ELSE(17,17)
#define XPOS_01H PBL_IF_ROUND_ELSE(18,23)
#define XPOS_02H PBL_IF_ROUND_ELSE(38,33)
#define XPOS_03H PBL_IF_ROUND_ELSE(52,33)
#define XPOS_04H PBL_IF_ROUND_ELSE(39,33)
#define XPOS_05H PBL_IF_ROUND_ELSE(18,23)
#define XPOS_06H PBL_IF_ROUND_ELSE(17,17)
#define XPOS_07H PBL_IF_ROUND_ELSE(55,57)
#define XPOS_08H PBL_IF_ROUND_ELSE(76,67)
#define XPOS_09H PBL_IF_ROUND_ELSE(87,67)
#define XPOS_10H PBL_IF_ROUND_ELSE(72,67)
#define XPOS_11H PBL_IF_ROUND_ELSE(55,57)

#define YPOS_12H PBL_IF_ROUND_ELSE(78,74)
#define YPOS_01H PBL_IF_ROUND_ELSE(70,74)
#define YPOS_02H PBL_IF_ROUND_ELSE(44,44)
#define YPOS_03H PBL_IF_ROUND_ELSE(12,9)
#define YPOS_04H PBL_IF_ROUND_ELSE(21,26)
#define YPOS_05H PBL_IF_ROUND_ELSE(44,51)
#define YPOS_06H PBL_IF_ROUND_ELSE(54,54)
#define YPOS_07H PBL_IF_ROUND_ELSE(44,51)
#define YPOS_08H PBL_IF_ROUND_ELSE(21,26)
#define YPOS_09H PBL_IF_ROUND_ELSE(12,9)
#define YPOS_10H PBL_IF_ROUND_ELSE(44,44)
#define YPOS_11H PBL_IF_ROUND_ELSE(70,74)

#define XLENHOURS 40
#define YLENHOURS 40

#define CIRCLE_SECONDS_AREA true

#define CONFIG_SECONDS_HAND_INVERSED false
#define CONFIG_INFOLEFT_HAND_INVERSED false
#define CONFIG_INFORIGHT_HAND_INVERSED false



#define HOUR_MARKERS_COLOR GColorLightGray
#define MINUTE_MARKERS_COLOR GColorLightGray
#define HOUR_HAND_COLOR GColorLightGray
#define MINUTE_HAND_COLOR GColorWhite
#define SECONDS_HAND_COLOR  GColorVividCerulean
#define INFOLEFT_HAND_COLOR  GColorVividCerulean
#define INFORIGHT_HAND_COLOR GColorVividCerulean
#define INFOLEFT_CIRCLE_COLOR  GColorVividCerulean
#define INFORIGHT_CIRCLE_COLOR  GColorVividCerulean
#define CIRCLES_COLOR  GColorBlack

#define SUBSCRIBE_TO_BATTERY true
#define SUBSCRIBE_TO_HEALTH true
#define SHOWINFOCIRCLES true
#define SECONDS_FOR_POPUP 3000

#define DEBUG false